extends Node

@warning_ignore("unused_signal")
signal thrust_changed(actor: Actor, thrust: int, max_thrust: int)
@warning_ignore("unused_signal")
signal round_changed(round: int, max_round: int)
@warning_ignore("unused_signal")
signal phase_changed(actor: Actor, phase: Enums.game_states)
@warning_ignore("unused_signal")
signal log_request(message: String)
@warning_ignore("unused_signal")
signal game_over()
@warning_ignore("unused_signal")
signal target_change(to_actor: Actor)
@warning_ignore("unused_signal")
signal toggle_target(visibility: bool)
